# This is a sample aws-auth-patch.yml file. 
# Actual aws-auth-patch.yml will be created at /System/Volumes/Data/private/tmp/aws-auth-patch.yml path.

apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::859131169493:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-ND7BL91GHU9R
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::859131169493:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-10-08T07:39:50Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1419"
  uid: dd6ecdd5-7be5-47c8-aab0-2951538419a5
